In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('bikes.csv')

In [4]:
df

,datetime,season,holiday,workingday,weather,temp,humidity,windspeed,casual,registered,rented_bikes_count
0,2011-01-01 00:00:00,Spring,0.0,0.0,Clear,9.84,81.0,NaN,3,13,16
1,2011-01-01 01:00:00,Spring,0.0,0.0,NaN,9.02,80.0,0.0000,8,32,40
2,2011-01-01 02:00:00,Spring,0.0,0.0,Clear,9.02,NaN,0.0000,5,27,32
3,2011-01-01 03:00:00,Spring,0.0,0.0,Clear,9.84,75.0,0.0000,3,10,13
4,2011-01-01 04:00:00,NaN,0.0,0.0,Clear,NaN,75.0,NaN,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...
10881,2012-12-19 19:00:00,Winter,0.0,1.0,Clear,15.58,50.0,26.0027,7,329,336
10882,2012-12-19 20:00:00,Winter,0.0,1.0,NaN,14.76,NaN,NaN,10,231,241
10883,2012-12-19 21:00:00,NaN,0.0,1.0,Clear,13.94,61.0,15.0013,4,164,168
10884,2012-12-19 22:00:00,Winter,NaN,1.0,Clear,13.94,NaN,6.0032,12,117,129
10885,2012-12-19 23:00:00,Winter,0.0,1.0,Clear,13.12,66.0,8.9981,4,84,88

In [89]:
df.head(20)

,datetime,season,workingday,weather,temp,humidity,windspeed,casual,registered,rented_bikes_count
0,2011-01-01 00:00:00,Spring,0.0,Clear,9.84,81.0,NaN,3,13,16
1,2011-01-01 01:00:00,Spring,0.0,NaN,9.02,80.0,0.0000,8,32,40
2,2011-01-01 02:00:00,Spring,0.0,Clear,9.02,NaN,0.0000,5,27,32
3,2011-01-01 03:00:00,Spring,0.0,Clear,9.84,75.0,0.0000,3,10,13
4,2011-01-01 04:00:00,NaN,0.0,Clear,NaN,75.0,NaN,0,1,1
5,2011-01-01 05:00:00,NaN,NaN,Mist,9.84,NaN,6.0032,0,1,1
6,2011-01-01 06:00:00,Spring,0.0,Clear,NaN,NaN,0.0000,2,0,2
7,2011-01-01 07:00:00,Spring,0.0,Clear,8.20,NaN,NaN,1,2,3
8,2011-01-01 08:00:00,Spring,0.0,NaN,9.84,NaN,0.0000,1,7,8
9,2011-01-01 09:00:00,Spring,0.0,Clear,NaN,76.0,0.0000,8,6,14
10,2011-01-01 10:00:00,Spring,0.0,Clear,15.58,76.0,NaN,12,24,36
11,2011-01-01 11:00:00,Spring,0.0,Clear,14.76,81.0,19.0012,26,30,56
12,2011-01-01 12:00:00,Spring,NaN,Clear,NaN,77.0,19.0012,29,55,84
13,2011-01-01 13:00:00,Spring,0.0,Mist,18.86,NaN,NaN,47,47,94
14,2011-01-01 14:00:00,Spring,0.0,Mist,18.86,72.0,19.0012,35,71,106
15,2011-01-01 15:00:00,Spring,0.0,Mist,18.04,77.0,19.9995,40,70,110
16,2011-01-01 16:00:00,Spring,0.0,Mist,17.22,82.0,19.9995,41,52,93
17,2011-01-01 17:00:00,Spring,NaN,Mist,18.04,82.0,19.0012,15,52,67
18,2011-01-01 18:00:00,Spring,0.0,Rainy,17.22,88.0,16.9979,9,26,35
19,2011-01-01 19:00:00,Spring,0.0,Rainy,17.22,NaN,16.9979,6,31,37

In [8]:
## Display Rented Bikes Count
df['rented_bikes_count']

0         16
1         40
2         32
3         13
4          1
        ...
10881    336
10882    241
10883    168
10884    129
10885     88
Name: rented_bikes_count, Length: 10886, dtype: int64

In [21]:
## Display Rented Bikes Count as well as DateTime -> Double Square Bracket
df[['datetime','rented_bikes_count']]

                  datetime  rented_bikes_count
0      2011-01-01 00:00:00                  16
1      2011-01-01 01:00:00                  40
2      2011-01-01 02:00:00                  32
3      2011-01-01 03:00:00                  13
4      2011-01-01 04:00:00                   1
...                    ...                 ...
10881  2012-12-19 19:00:00                 336
10882  2012-12-19 20:00:00                 241
10883  2012-12-19 21:00:00                 168
10884  2012-12-19 22:00:00                 129
10885  2012-12-19 23:00:00                  88

[10886 rows x 2 columns]

In [59]:
##Print temperature and rented bikes count if temperature is grater then 15
f= df[df['temp'] > 15]
f[['temp','rented_bikes_count']]

        temp  rented_bikes_count
10     15.58                  36
13     18.86                  94
14     18.86                 106
15     18.04                 110
16     17.22                  93
...      ...                 ...
10856  15.58                 525
10857  15.58                 353
10873  16.40                 200
10880  15.58                 569
10881  15.58                 336

[5615 rows x 2 columns]

In [54]:
##Display alternative Rows
df.iloc[:,::2]

,datetime,holiday,weather,humidity,casual,rented_bikes_count
0,2011-01-01 00:00:00,0.0,Clear,81.0,3,16
1,2011-01-01 01:00:00,0.0,NaN,80.0,8,40
2,2011-01-01 02:00:00,0.0,Clear,NaN,5,32
3,2011-01-01 03:00:00,0.0,Clear,75.0,3,13
4,2011-01-01 04:00:00,0.0,Clear,75.0,0,1
...,...,...,...,...,...,...
10881,2012-12-19 19:00:00,0.0,Clear,50.0,7,336
10882,2012-12-19 20:00:00,0.0,NaN,NaN,10,241
10883,2012-12-19 21:00:00,0.0,Clear,61.0,4,168
10884,2012-12-19 22:00:00,NaN,Clear,NaN,12,129
10885,2012-12-19 23:00:00,0.0,Clear,66.0,4,88

In [79]:
## Check number of null values present in  registered column
print(df['registered'].isnull().sum())

0

In [80]:
## Check number of null values present in  temperature column
print(df['temp'].isnull().sum())

2782

In [82]:
print(df['temp'].duplicated().sum())

10836

In [83]:
print(df['holiday'].duplicated().sum())

10883

In [ ]:
del df['holiday']

In [87]:
df

,datetime,season,workingday,weather,temp,humidity,windspeed,casual,registered,rented_bikes_count
0,2011-01-01 00:00:00,Spring,0.0,Clear,9.84,81.0,NaN,3,13,16
1,2011-01-01 01:00:00,Spring,0.0,NaN,9.02,80.0,0.0000,8,32,40
2,2011-01-01 02:00:00,Spring,0.0,Clear,9.02,NaN,0.0000,5,27,32
3,2011-01-01 03:00:00,Spring,0.0,Clear,9.84,75.0,0.0000,3,10,13
4,2011-01-01 04:00:00,NaN,0.0,Clear,NaN,75.0,NaN,0,1,1
...,...,...,...,...,...,...,...,...,...,...
10881,2012-12-19 19:00:00,Winter,1.0,Clear,15.58,50.0,26.0027,7,329,336
10882,2012-12-19 20:00:00,Winter,1.0,NaN,14.76,NaN,NaN,10,231,241
10883,2012-12-19 21:00:00,NaN,1.0,Clear,13.94,61.0,15.0013,4,164,168
10884,2012-12-19 22:00:00,Winter,1.0,Clear,13.94,NaN,6.0032,12,117,129
10885,2012-12-19 23:00:00,Winter,1.0,Clear,13.12,66.0,8.9981,4,84,88

In [91]:
df.iloc[::1000,::2]

                  datetime  workingday   temp  windspeed  registered
0      2011-01-01 00:00:00         0.0   9.84        NaN          13
1000   2011-03-06 03:00:00         0.0  17.22        NaN           9
2000   2011-05-10 06:00:00         1.0  17.22     8.9981         103
3000   2011-07-13 22:00:00         1.0  27.88    12.9980         136
4000   2011-09-17 17:00:00         0.0  21.32    15.0013         218
5000   2011-12-02 10:00:00         1.0  12.30        NaN          89
6000   2012-02-06 06:00:00         1.0   6.56        NaN          72
7000   2012-04-10 00:00:00         1.0  18.04        NaN          23
8000   2012-06-13 17:00:00         NaN  29.52        NaN         782
9000   2012-08-17 09:00:00         1.0  28.70     7.0015         320
10000  2012-11-02 01:00:00         1.0  13.12    11.0014          19